CREATE TABLE usuario
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    last_name           VARCHAR(255),
    cpf                 VARCHAR(255),
    email               VARCHAR(255),
    username            VARCHAR(255),
    password            VARCHAR(255),
    role                VARCHAR(255) DEFAULT 'CLIENTE' NOT NULL ,
    active              BOOLEAN DEFAULT TRUE,
    is_late             BOOLEAN DEFAULT FALSE,
    account_expired     BOOLEAN DEFAULT FALSE NOT NULL,
    account_locked      BOOLEAN DEFAULT FALSE NOT NULL,
    credentials_expired BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);
ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_username UNIQUE (username);
CREATE TABLE filme_conceito
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid      UUID DEFAULT random_uuid()              NOT NULL,
    nome      VARCHAR(255),
    genero    VARCHAR(255),
    descricao VARCHAR(255),
    CONSTRAINT pk_filmeconceito PRIMARY KEY (id)
);
CREATE TABLE filme_real
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_alugado        BOOLEAN DEFAULT FALSE                   NOT NULL,
    uuid              UUID    DEFAULT random_uuid(),
    filme_conceito_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_filmereal PRIMARY KEY (id)
);

ALTER TABLE filme_real
    ADD CONSTRAINT FK_FILMEREAL_ON_FILME_CONCEITO FOREIGN KEY (filme_conceito_id) REFERENCES filme_conceito (id);
CREATE TABLE aluguel
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID DEFAULT RANDOM_UUID(),
    horario_aluguel   TIMESTAMP,
    horario_devolucao TIMESTAMP,
    usuario_id        BIGINT                                  NOT NULL,
    filme_concreto_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_aluguel PRIMARY KEY (id)
);

ALTER TABLE aluguel
    ADD CONSTRAINT FK_ALUGUEL_ON_FILME_CONCRETO FOREIGN KEY (filme_concreto_id) REFERENCES filme_real (id);

ALTER TABLE aluguel
    ADD CONSTRAINT FK_ALUGUEL_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (id);