CREATE TABLE usuario
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    last_name           VARCHAR(255),
    cpf                 VARCHAR(255),
    email               VARCHAR(255),
    username            VARCHAR(255),
    password            VARCHAR(255),
    role                VARCHAR(255),
    active              BOOLEAN DEFAULT TRUE,
    is_late             BOOLEAN DEFAULT FALSE,
    account_expired     BOOLEAN DEFAULT FALSE NOT NULL,
    account_locked      BOOLEAN DEFAULT FALSE NOT NULL,
    credentials_expired BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

ALTER TABLE usuario
    ADD CONSTRAINT uc_usuario_username UNIQUE (username);